[pytest]
testpaths = Tests
addopts = -v --alluredir=allure-results
markers =
    unit: unit tests
    integration: integration tests
    ui: Selenium UI tests
    smoke: quick smoke checks
    critical: critical checks